export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_NESTED_CATEGORY = 'ADD_NESTED_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const RENAME_CATEGORY = 'RENAME_CATEGORY';

export const CHANGE_TASK_LOCATION = 'CHANGE_TASK_LOCATION';